// <auto-generated />
using System;
using Capitals.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Capitals.Migrations
{
    [DbContext(typeof(QuizContext))]
    partial class QuizContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Capitals.Models.Capital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("WordlCapitalId");

                    b.HasKey("Id");

                    b.HasIndex("WordlCapitalId");

                    b.ToTable("Capital");
                });

            modelBuilder.Entity("Capitals.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int?>("WordlCapitalId");

                    b.HasKey("Id");

                    b.HasIndex("WordlCapitalId");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("Capitals.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Capitals.Models.WordlCapital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Difficulty");

                    b.HasKey("Id");

                    b.ToTable("WorldCapitals");
                });

            modelBuilder.Entity("Capitals.Models.Capital", b =>
                {
                    b.HasOne("Capitals.Models.Country", "Country")
                        .WithOne("Capital")
                        .HasForeignKey("Capitals.Models.Capital", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Capitals.Models.WordlCapital")
                        .WithMany("Capitals")
                        .HasForeignKey("WordlCapitalId");
                });

            modelBuilder.Entity("Capitals.Models.Country", b =>
                {
                    b.HasOne("Capitals.Models.WordlCapital")
                        .WithMany("Countries")
                        .HasForeignKey("WordlCapitalId");
                });
#pragma warning restore 612, 618
        }
    }
}
